### ISSUE TITLE
Document mistake : 'moon' should be 'moonscript' in code-runner.executorMap.

### ISSUE THREAD

**Issue by harrisyu** [AlRado/Visual-Code-TIC-80#5]
Document mistake : 'moon' should be 'moonscript' in
'''js
    // Set the executor of each language.
    "code-runner.executorMap": {
        "javascript":   "tic.exe C:\\Users\\alrad\\AppData\\Roaming\\com.nesbox.tic\\TIC-80\\$fileNameWithoutExt.tic -code $fullFileName",
        "lua":          "tic.exe C:\\Users\\alrad\\AppData\\Roaming\\com.nesbox.tic\\TIC-80\\$fileNameWithoutExt.tic -code $fullFileName",      
        "moon":         "tic.exe C:\\Users\\alrad\\AppData\\Roaming\\com.nesbox.tic\\TIC-80\\$fileNameWithoutExt.tic -code $fullFileName"      
    },
'''

or code runner will not find the right language.

**Comment by AlRado** [comment]
You are right, I corrected the mistake.
Thanks for your feedback.
