### ISSUE TITLE
new setup for tic 0.50

### ISSUE THREAD

**Issue by ambyra** [AlRado/Visual-Code-TIC-80#6]
1. install coderunner vscode plugin
2.  add tic80 executable to path environment variable
3. edit vscode preferences:
```
    "code-runner.executorMap": {
        "javascript":   "tic80 $fullFileName"     
    },
    "code-runner.saveFileBeforeRun": true

```

**Comment by AlRado** [comment]
Thank you for the amendment.
Yes, you can add a tic80 executable to path environment variable or write "code-runner.cwd": "C:\\Program Files\\TIC-80\\" in settings.
Only you missed the -code ("javascript":   "tic80 -code $fullFileName" )

**Comment by AlRado** [comment]
Fixed.

**Comment by ambyra** [comment]
-code doesn’t work on new 0.5 pro version, because graphics are built into js file. 

I guess you can post two different settings for pro and regular versions.
